### PR TITLE
Fix to Racket implementation + compilation.

### PR DESCRIPTION
**Pull request by gabriel-fallen**
There was a stupid error which caused Racket to do nothing which it does blazingly fast. Now it actually does copy data.
I've added compilation/executable generation step but it doesn't really increase performance.

### CODE REVIEW

**Comment by caml-programmer** [comment]
Now racket results: 24 seconds, but 13 already be present.

**Comment by gabriel-fallen** [comment]
How come?
On my laptop (Linux 4.2.0-41-generic #48-Ubuntu SMP) _without_ SSD all scripting languages I've tried (Racket, Dart, Python) copy 5GB file to `/dev/null` in under 1min (40-55 seconds). And copy to a file in under 2 min.

**Comment by caml-programmer** [comment]
First version of test works with 2^17 blocks of data and 5Gb datafile complete allocated in the memory (VFS). I don't register non-cached results. The function `copy-port` worked with small buffer size - 4K and it's some slowly that previous versions. You can try running this test on smaller datafile, e.g. 512 Mb to reproduce it behavior (check for memsize > datafilesize).

**Comment by gabriel-fallen** [comment]
Actually, I can't reproduce your results. I do this:

```
time make test
./cat >/dev/null

real 0m53.481s
user 0m3.536s
sys  0m4.052s
```

This was "fast" Racket implementation. "Slow" one works around the same time (45-55 seconds, it varies in this range for both implementations). That's for 5GB file.

So I don't get how you've got 13 seconds. I doubt you have much slower machine than I do. Maybe, I measure something wrong? Or you do?

P.S. We can switch to Russian for clarity. I doubt any non-russian speaker follows this discussion. :)

**Pull request merged**
